import type { Metadata } from "next";

import { AppRouteLoading } from "./_components/app-route-loading";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <AppRouteLoading>{children}</AppRouteLoading>
      </body>
    </html>
  );
}
